### ISSUE TITLE
Issues with the WUI

### ISSUE THREAD

**Issue by QuCMGisaia** [gisaia/ARLAS-wui#463]
- [ ] gisaia/ARLAS-wui#530

![Screenshot 2022-04-21 at 14 42 01](https://user-images.githubusercontent.com/104018401/164678078-64c4f4e3-7333-453e-8c15-9b0515f6b990.png)

- [ ] gisaia/ARLAS-wui-builder#841

![Screenshot 2022-04-21 at 14 47 59](https://user-images.githubusercontent.com/104018401/164678493-c487e296-0e1e-4ebf-bf6d-ede2d17c10cb.png)

- [ ] gisaia/ARLAS-wui#531

<img width="1432" alt="Screenshot 2022-04-29 at 16 03 02" src="https://user-images.githubusercontent.com/104018401/165959996-66948bac-ee8c-445f-ac31-27106da7c55c.png">
 
- [x] When switching from include to exclude, the fields of the powerbar are not unselected
- [ ] gisaia/ARLAS-wui#534
- [ ] gisaia/ARLAS-wui#532
- [ ] gisaia/ARLAS-wui#533

**Comment by MohamedHamouGisaia** [comment]
Closing because it includes many bullet points. Each one has been transformed to a github issue.
